# Generated by Django 5.1.2 on 2024-10-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_eventos_evento_rename_roles_role_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
    ]
