# Generated by Django 5.1.2 on 2024-10-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_user_last_login_alter_user_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='correo',
            new_name='email',
        ),
    ]
