# Generated by Django 5.1.2 on 2024-10-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_remove_user_last_login_alter_user_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
